# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks

# desc: no /:year/:month/:day/
permalink:        /:title

# Setup
title:            Mirco Zeiss
description:      My private blog about web engineering. Expect posts about JavaScript, Node.js, AngularJS and NoSQL databases.
url:              http://mircozeiss.com/

author:
  name:           Mirco Zeiss
  email:          mirco.zeiss@gmail.com

# desc: maximum number of Posts you’d like to be displayed per page
paginate:         100

exclude:          [node_modules, Gruntfile.js, package.json]
