# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks

# desc: no .html at the end
permalink:        pretty

# Setup
title:            Mirco Zeiss
#tagline:          'A Jekyll theme'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://mircozeiss.com/

author:
  name:           'Mirco Zeiss'
  url:            https://twitter.com/zeMirco

# desc: maximum number of Posts you’d like to be displayed per- page
paginate:         5

# Custom vars
#version:          1.0.0

#github:
#  repo:           https://github.com/poole/lanyon
